### ISSUE TITLE
机器人只要被踢出群，就无法再次收到加群邀请事件了

### ISSUE THREAD

**Issue by rockswang** [IOTQQ/IOTQQ#11]
首次被邀请的时候，机器人能够收到ON_EVENT_GROUP_ADMINSYSNOTIFY事件，并可以调用AnswerInviteGroup自动接受邀请，但是如果被踢出群，然后再次被邀请，就收不到任何事件通知了

**Comment by rockswang** [comment]
发现邀请发出的时刻，iotqq的日志实际是有反应的，但是显然此消息并没有被解析并发送给ws客户端。
IOTQQ后台的反应如下：
2020/01/03 17:56:46.581 [I]  
============== 
 MessageSvc_PushNotify  wMsgType 87  wGeneralFlag 1
==============

2020/01/03 17:56:46.581 [M]  Task Done By Worker Id:36 Cost Time:90.224µs TotalworkersNum:50  
2020/01/03 17:56:46.653 [M]  Task Done By Worker Id:24 Cost Time:37.572µs TotalworkersNum:50  
2020/01/03 17:56:46.714 [I]  
============== 
 MessageSvc_PushNotify  wMsgType 166  wGeneralFlag 1
==============

**Comment by IOTQQ** [comment]
已修复
