### ISSUE TITLE
调用WebAPI发送文本型群消息无效

### ISSUE THREAD

**Issue by nepsyn** [IOTQQ/IOTQQ#16]
尝试了很多次调用WebAPI向群发送文本消息
请求body：

```
 {
 "toUser": 1049398991,
 "sendToType": 2,
 "sendMsgType": "TextMsg",
 "content": "框架发送消息",
 "groupid": 0,
 "atUser": 0
}
```

得到的都是：

```
{
    "Msg": "",
    "Ret": 0
}
```

但是实际上没有发送成功，程序也没有任何错误提示。
发送JsonMsg类型就没有问题。

**Comment by IOTQQ** [comment]
请详细描述一下问题 进群截图反馈一下 - -

**Comment by IOTQQ** [comment]
> 尝试了很多次调用WebAPI向群发送文本消息
> 请求body：
> 
> ```
>  {
>  "toUser": 1049398991,
>  "sendToType": 2,
>  "sendMsgType": "TextMsg",
>  "content": "框架发送消息",
>  "groupid": 0,
>  "atUser": 0
> }
> ```
> 
> 得到的都是：
> 
> ```
> {
>     "Msg": "",
>     "Ret": 0
> }
> ```
> 
> 但是实际上没有发送成功，程序也没有任何错误提示。
> 发送JsonMsg类型就没有问题。

请详细描述一下问题 进群截图反馈一下 - -

**Comment by IOTQQ** [comment]
小号🎺屏蔽 TX把消息吃了   🎺 挂机几天即可
