### ISSUE TITLE
API 请求 URL 多一个斜杠导致 500 错误

### ISSUE THREAD

**Issue by qwqcode** [IOTQQ/IOTQQ#17]
## 感谢 dalao 开发维护如此 awesome 的项目！！ 吹爆！

有一个不起眼的小瑕疵，dalao 可以修复一下下

如果请求地址是  `http://127.0.0.1:8888/v1//LuaApiCaller?qq=1111&funcname=SendMsg&timeout=10` (多了个斜杠 `/`)，会导致 500 错误

在 Windows 环境下部署的 IOTQQ，如题和如下图 qwq：

![image](https://user-images.githubusercontent.com/22412567/75010823-18348700-54b9-11ea-8678-ee8fb04aef54.png)
![image](https://user-images.githubusercontent.com/22412567/75010836-2387b280-54b9-11ea-8cc8-40a1acc2fc30.png)

当然，在引用 IOTQQ，也可以自行 patch 一下，如 JS 这样处理一下 `WEB_API.replace(/\/+$/, '')` https://github.com/rockswang/qqcensorbot/pull/1

但还是希望 dalao 简单处理下，感谢！！！

**Comment by qwqcode** [comment]
因为我还不太了解 lua 语言，所以就不发起 PR 了，dalao 来修复吧~~

**Comment by IOTQQ** [comment]
> 因为我还不太了解 lua 语言，所以就不发起 PR 了，dalao 来修复吧~~

不属于bug  webapi 正常就1个反斜杠/ 在加一个就属于另外一个路径了 可能是go的解析问题 不是大问题呀 一般手误会多打出2个//

**Comment by qwqcode** [comment]
> 不属于bug webapi 正常就1个反斜杠/ 在加一个就属于另外一个路径了 可能是go的解析问题 不是大问题呀 一般手误会多打出2个//

![20200225125324](https://user-images.githubusercontent.com/22412567/75216111-e4fe3a80-57cd-11ea-8275-57e73b734802.png)
![20200225125502](https://user-images.githubusercontent.com/22412567/75216158-0d863480-57ce-11ea-8d06-5ca4f6895e28.jpg)

求大佬科普，为什么还是同一个路径？
