### ISSUE TITLE
快速调用WebAPI接口的问题

### ISSUE THREAD

**Issue by Runc2333** [IOTQQ/IOTQQ#20]
使用贵项目实现TimeBot时，需要向多个群聊发送图片。使用的语言是Node.js，在同时发起多个异步网络请求后，贵项目似乎无法正确处理收到的请求，而会导致全部图片都发送失败。

暂时可通过设置延时的方式按顺序发送(等上一个请求完成后再发起下一个请求)来解决该问题，但还是希望贵项目能解决该问题/提供同时向多个对象发送消息的功能。

**Comment by IOTQQ** [comment]
emm 内置坑 快速群发 恶意营销群发 导致的 。正常机器人回复就好啦～
