### ISSUE TITLE
请问下这样一直登录不成功是因为什么呢？

### ISSUE THREAD

**Issue by langzicx** [IOTQQ/IOTQQ#23]
![login](https://s1.ax1x.com/2020/04/02/GJHlND.png)
请问下这样一直登录不成功是因为什么呢？

**Comment by langzicx** [comment]
树莓派上使用的。
2个qq都是这样

**Comment by IOTQQ** [comment]
> 树莓派上使用的。
> 2个qq都是这样
初始化成功了嗎
