### ISSUE TITLE
WebAPI 发送文本无效

### ISSUE THREAD

**Issue by heye0507** [IOTQQ/IOTQQ#24]
BUG:
调用WebAPI接口, 尝试发送文本信息到群聊， 群内无法收到消息

Body如下
`toUser: 821997254,
sendToType: 2,
sendMsgType: 'TextMsg'
content: 'test',
groupid: 0,
atUser: 0,
replayInfo: null`

得到的返回值
`Msg: ,
Ret:  0`

运行IOTQQ的后台记录可以看到
2020/04/08 06:32:16.964 [M]  Task Done By Worker Id:49 Cost Time:6.417153ms TotalworkersNum:50  
2020/04/08 06:32:17.246 [M]  before hook
2020/04/08 06:32:17.250 [C]  Api_LuaCaller FuncName SendMsg
2020/04/08 06:32:17.481 [M]  Task Done By Worker Id:37 Cost Time:9.785µs TotalworkersNum:50  
2020/04/08 06:32:17.483 [M]  POST       /v1/LuaApiCaller?qq=65685977&funcname=SendMsg   236.686296ms
2020/04/08 06:32:18.312 [M]  Task Done By Worker Id:29 Cost Time:23.568µs TotalworkersNum:50

**Comment by sddwt** [comment]
有没有试过lua插件内发送？
有可能是框架原因，因为我也遇到了群聊无法发送文本和图片消息，私聊可以

**Comment by easyworld** [comment]
多挂几天

**Comment by IOTQQ** [comment]
小号嘛 - - 挂机几天 屏蔽了
