### ISSUE TITLE
群聊Msg和Pic类型无法发送（在手机登陆后出现）

### ISSUE THREAD

**Issue by sddwt** [IOTQQ/IOTQQ#26]
BUG：在新的服务器上登陆框架后，群聊功能完全正常；一旦手机登陆后群聊就无法发送文本和图片（试过了三次均是这种情况），框架没有发送内容输出，接收是正常的。
一开始以为是我服务器的原因，换了新的服务器后发送正常，一登陆手机版本就立马无法发送了

**Comment by IOTQQ** [comment]
刷新一下key 试试 /v1/RefreshKeys

**Comment by sddwt** [comment]
感谢回复，经过测试发现不仅仅是手机登陆后，可能一段时间后也会出现这个问题！
接口访问后，输出是[] offline

**Comment by sddwt** [comment]
刚刚找了其他类型的项目，发现有可能是我的账号被怀疑盗号，我试着挂几天看看

**Comment by IOTQQ** [comment]
小号吧 挂机几天 一般异地登陆都是秒封  解冻一下就好了

**Comment by sddwt** [comment]
请问付费计划如何，裙多少?
开发者很用心，想要尽量支持一下，谢谢
