### ISSUE TITLE
可以发文字在前，图片在后的消息吗？

### ISSUE THREAD

**Issue by ZHX98** [IOTQQ/IOTQQ#3]
当我用PicMsg，消息的格式都是图片在上面，字在下面。希望可以支持文字在上，图片在下。

**Comment by IOTQQ** [comment]
好的 我研究研究 字段顺序的位置哈

**Comment by KkEeVvIiNnn** [comment]
请问这个问题解决了嘛

**Comment by IOTQQ** [comment]
早就解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "KkEeVvIiNnn"<notifications@github.com&gt;; 
发送时间: 2020年7月27日(星期一) 晚上9:41
收件人: "IOTQQ/IOTQQ"<IOTQQ@noreply.github.com&gt;; 
抄送: "hobo"<1700487478@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [IOTQQ/IOTQQ] 可以发文字在前，图片在后的消息吗？ (#3)





 
请问这个问题解决了嘛
