### ISSUE TITLE
软件运行的流程是怎样的？

### ISSUE THREAD

**Issue by chelunfu** [IOTQQ/IOTQQ#33]
申请了token后，扫描登录后，软件后台会记录我的登录信息么，或者我的聊天信息也会记录？为什么更新新的API后，会自动往不同的群里发信息？是你们服务端控制的么？还是我哪里没设置好。手机端显示MAC登录，是否有一台mac电脑在云端运行，把收到的消息在下发到软件二进制客户端。然后我们在用wapapi来获取？

**Comment by IOTQQ** [comment]
自己分析一下客户端 即可 我不记录tx也会记录的
