### ISSUE TITLE
程序报错终止

### ISSUE THREAD

**Issue by shirakagi** [IOTQQ/IOTQQ#37]
panic: interface conversion: interface {} is nil, not string

goroutine 1936 [running]:
main.(*Sub_0xLdYSt).Sub_0xrYxWc.func1(0xc00021a400, 0x3a, 0x200, 0x10d9d40, 0xc0002ba9a0, 0x18)
        /Volumes/UDISK/GoPath/src/NewNewQQToy/Websocket.go:758 +0x152
created by main.(*Sub_0xLdYSt).Sub_0xrYxWc
        /Volumes/UDISK/GoPath/src/NewNewQQToy/Websocket.go:753 +0x4a6

**Comment by IOTQQ** [comment]
等修复这个bug

**Comment by IOTQQ** [comment]
fix v3.0.6
