### ISSUE TITLE
2.0.1版无法登录

### ISSUE THREAD

**Issue by rockswang** [IOTQQ/IOTQQ#8]
分别在CentOS7.6和Window10上测试过，现象均一致。
第一次尝试，阿里云新加坡节点+CentOS7.6
第二次尝试，腾讯云上海节点+CentOS7.6
第三次尝试，本地Windows10
使用github账号：ipchi9012

具体流程：
1. 配置github，包括产生token, 设置webhook
2. 设置IOTQQ，修改端口号、token, webhookUrl
3. 在本地Windows10时，用SSH启动内网穿透
4. 启动IOTQQ
5. 确保公网的WebhookUrl返回ok, 访问Github/InstallService返回ok，但是后台未如文档中所言返回Auth初始化完成
6. 访问二维码页面，扫码登录，显示登录中，但是不成功，见截图
![QQ图片20191205180348](https://user-images.githubusercontent.com/2248386/70225243-9f5f4200-1789-11ea-9572-e6fa6595dc5e.png)

**Comment by rockswang** [comment]
删除Bot-Notify仓库之后重新初始化就ok了，谢谢Q群里大佬们的帮助

**Comment by IOTQQ** [comment]
> 删除Bot-Notify仓库之后重新初始化就ok了，谢谢Q群里大佬们的帮助

感谢提交issuse 多多测试 发现bug会有惊喜哦～
